name:                haskell-stack
version:             0.1.0.0
github:              "githubuser/haskell-stack"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-stack#readme>

dependencies:
- base >= 4.7 && < 5
- req
- bytestring
- aeson
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

# 複数の実行ファイルを用意する
# see https://zenn.dev/toyboot4e/scraps/a84934cda8b49b#comment-322967a3875a19
_exe-defs: &exec-default
  source-dirs: app
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  other-modules: []
  dependencies:
    - haskell-stack

library:
  source-dirs: src

executables:
  # haskell-stack-exe:
  #   main:                Main.hs
  #   source-dirs:         app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - haskell-stack
  Main-exec:
    <<: *exec-default
    main: Main.hs
  Hello-exec:
    <<: *exec-default
    main: Hello.hs

tests:
  haskell-stack-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-stack
